// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drpjzpuxcjwswumdbikr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRycGp6cHV4Y2p3c3d1bWRiaWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjA5ODUsImV4cCI6MjA3Mjg5Njk4NX0._NdvMIylpxVeBGkpMCD7a0u1qh1T8K9LKrPsjmVVMj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});